#!/usr/bin/env python3
"""Generate include/app_shared_config.generated.h from .env.

Called as a PlatformIO pre:extra_script so that firmware macros for MQTT and
shared thresholds stay in sync with the root .env (the single source of truth).

Env vars whose name matches a key below are written as #define macros into the
output header.  Env vars not listed here (WIFI_*, timings, pins) remain
exclusively in include/app_config.h.
"""

import os
import re
from pathlib import Path

ENV_TO_MACRO = {
    "MQTT_BROKER_HOST": str,
    "MQTT_BROKER_PORT": int,
    "MQTT_USER": (str, "MQTT_USERNAME"),
    "MQTT_PASSWORD": str,
    "MQTT_TOPIC_BASE": str,
    "HARDWARE_DEVICE_ID": (str, "DEVICE_ID"),
    "CO_SEGURO_MAX_PPM": float,
    "CO_PRECAUCION_MAX_PPM": float,
    "CO_PELIGRO_MAX_PPM": float,
    "CO_URGENTE_MIN_PPM": float,
    "MQ7_ADC_SEGURO_RAW_MAX": int,
    "MQ7_ADC_PRECAUCION_RAW_MAX": int,
    "MQ7_ADC_PELIGRO_RAW_MAX": int,
    "MQ7_ADC_URGENTE_RAW_MIN": int,
    "MQ7_ADC_SATURATION_RAW": int,
}

try:
    Import("env")  # PlatformIO injects this in the build hook context
    _in_pio = True
except Exception:
    _in_pio = False


def _project_root() -> Path:
    if _in_pio:
        return Path(env.subst("$PROJECT_DIR"))
    return Path(__file__).resolve().parent.parent


def _format_value(raw: str, typ: type) -> str:
    if typ is int:
        return str(int(raw))
    if typ is float:
        return f"{float(raw)}f"
    if typ is str:
        escaped = raw.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return raw


def generate(output_path: Path) -> None:
    lines = [
        "#pragma once",
        "",
        "// Automatically generated by scripts/generate_firmware_shared_config.py",
        "// from .env at build time.  Do not edit manually.",
        "",
    ]

    for env_key, spec in ENV_TO_MACRO.items():
        raw = os.environ.get(env_key)
        if raw is None:
            continue

        if isinstance(spec, tuple):
            typ, macro_name = spec
        else:
            typ = spec
            macro_name = env_key

        lines.append(f"#define {macro_name} {_format_value(raw, typ)}")

    lines.append("")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[generate] Wrote {output_path}")


def _load_dotenv(path: Path) -> None:
    """Load key=value lines from .env into os.environ (without overriding)."""
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r'^export\s+', line)
        if m:
            line = line[m.end():]
        key, _, raw_val = line.partition("=")
        key = key.strip()
        raw_val = raw_val.strip().strip("\"'")
        if key and key not in os.environ:
            os.environ[key] = raw_val


# Entry point — works both in PlatformIO and standalone.
root = _project_root()
_load_dotenv(root / ".env")
generate(root / "include/app_shared_config.generated.h")
